version: '3.9'

services:
  enshrouded:
    image: sknnr/enshrouded-dedicated-server:v2.0.1
    ports:
      - "15636:15636/udp"
      - "15637:15637/udp"
    env_file:
      - default.env
    volumes:
      - ./savegame:/home/steam/enshrouded/savegame
